### ISSUE TITLE
Fail on yarn run build

### ISSUE THREAD

**Issue by miguelgargallo** [joschan21/bookbuddy#1]
log

```
> chatbot@0.1.0 build
> next build

info  - Loaded env from E:\bookbuddy\.env
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

Failed to compile.

HookWebpackError: File E:\bookbuddy\.next\server\app\favicon.ico\route.js does not exist.
    at makeWebpackError (E:\bookbuddy\node_modules\next\dist\compiled\webpack\bundle5.js:28:308185)
    at E:\bookbuddy\node_modules\next\dist\compiled\webpack\bundle5.js:28:105236
    at eval (eval at create (E:\bookbuddy\node_modules\next\dist\compiled\webpack\bundle5.js:13:28771), <anonymous>:57:1)
    at E:\bookbuddy\node_modules\next\dist\compiled\webpack\bundle5.js:28:68649
    at E:\bookbuddy\node_modules\next\dist\build\webpack\plugins\next-trace-entrypoints-plugin.js:420:143
-- inner error --
Error: File E:\bookbuddy\.next\server\app\favicon.ico\route.js does not exist.
    at Job.emitDependency (E:\bookbuddy\node_modules\next\dist\compiled\@vercel\nft\index.js:1:39473)
    at async Promise.all (index 6)
    at async nodeFileTrace (E:\bookbuddy\node_modules\next\dist\compiled\@vercel\nft\index.js:1:35430)
    at async E:\bookbuddy\node_modules\next\dist\build\webpack\plugins\next-trace-entrypoints-plugin.js:141:28
    at async Span.traceAsyncFn (E:\bookbuddy\node_modules\next\dist\trace\trace.js:97:20)
    at async TraceEntryPointsPlugin.createTraceAssets (E:\bookbuddy\node_modules\next\dist\build\webpack\plugins\next-trace-entrypoints-plugin.js:95:9)
caused by plugins in Compilation.hooks.processAssets
Error: File E:\bookbuddy\.next\server\app\favicon.ico\route.js does not exist.
    at Job.emitDependency (E:\bookbuddy\node_modules\next\dist\compiled\@vercel\nft\index.js:1:39473)
    at async Promise.all (index 6)
    at async nodeFileTrace (E:\bookbuddy\node_modules\next\dist\compiled\@vercel\nft\index.js:1:35430)
    at async E:\bookbuddy\node_modules\next\dist\build\webpack\plugins\next-trace-entrypoints-plugin.js:141:28
    at async Span.traceAsyncFn (E:\bookbuddy\node_modules\next\dist\trace\trace.js:97:20)
    at async TraceEntryPointsPlugin.createTraceAssets (E:\bookbuddy\node_modules\next\dist\build\webpack\plugins\next-trace-entrypoints-plugin.js:95:9)


> Build failed because of webpack errors
info  - Creating an optimized production build .
```

**Comment by miguelgargallo** [comment]
Lets deploy on Vercel with my .env variables:

![imagen](https://user-images.githubusercontent.com/5947268/235359891-96b0c27e-2d93-4e5f-b6ab-94f6cfc3888d.png)

**Comment by miguelgargallo** [comment]
On Vercel it compiles correctly

![imagen](https://user-images.githubusercontent.com/5947268/235359947-87d52f29-7913-4290-91bc-3ecb923913e7.png)

**Comment by miguelgargallo** [comment]
(on local build fails, vercel seems to not have any error)
